<?php
$data = array (
  'isvs1' => '0',
  'isvs2' => '0',
  'isvs3' => '0',
  'isvs4' => '0',
  'isvs5' => '0',
  'isAuto' => '0',
  'isAndroidOS' => '3',
  'isBlackBerryOS' => '2',
  'isPalmOS' => '2',
  'isSymbianOS' => '2',
  'isWindowsMobileOS' => '2',
  'isWindowsPhoneOS' => '2',
  'isiOS' => '3',
  'isMeeGoOS' => '2',
  'isMaemoOS' => '1',
  'isJavaOS' => '1',
  'iswebOS' => '2',
  'isbadaOS' => '2',
  'isBREWOS' => '1',
  'isOther' => '2',
  'isTablet' => '4',
  'isIE' => '5',
  'isFirefox' => '5',
  'isChrome' => '5',
  'isSafari' => '5',
  'isOpera' => '5',
  'iswebOther' => '5',
);
?>